# Generated by Django 4.2.1 on 2023-05-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ineffable_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('dob', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=30)),
                ('mark1', models.IntegerField()),
                ('mark2', models.IntegerField()),
                ('mark3', models.IntegerField()),
                ('percentage', models.IntegerField()),
                ('address', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
    ]
