# Generated by Django 4.2.1 on 2023-05-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ineffable_app', '0002_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlogin',
            name='adminemail',
            field=models.EmailField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
