# Generated by Django 4.2.1 on 2023-05-10 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ineffable_app', '0005_alter_student_dob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
