# Generated by Django 4.2.1 on 2023-06-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ineffable_app', '0008_centerregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CenterRegistration',
        ),
    ]
