# Generated by Django 4.2.1 on 2023-06-10 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ineffable_app', '0011_centre_register_student_delete_centre_registeration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Centre_Register_Student',
        ),
    ]
