# Generated by Django 4.2.1 on 2023-06-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ineffable_app', '0012_delete_centre_register_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentreRegisterStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20)),
                ('mother_name', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=20)),
                ('rollno', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('Dob', models.DateField()),
                ('centre_name', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=40)),
                ('duration', models.DateField()),
                ('examheldon', models.DateField()),
                ('percent', models.IntegerField()),
                ('grade', models.CharField(max_length=2)),
                ('session', models.CharField(max_length=20)),
                ('centre_code', models.IntegerField()),
                ('dateofissue', models.DateField()),
                ('remark', models.CharField(max_length=2)),
                ('mark_s1', models.IntegerField()),
                ('mark_s2', models.IntegerField()),
                ('mark_s3', models.IntegerField()),
                ('mark_s4', models.IntegerField()),
                ('mark_s5', models.IntegerField()),
                ('written_mark', models.IntegerField()),
                ('practical_mark', models.IntegerField()),
                ('assignment_mark', models.IntegerField()),
                ('viva_mark', models.IntegerField()),
            ],
        ),
    ]
