# Generated by Django 4.2.1 on 2023-06-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ineffable_app', '0013_centreregisterstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centreregisterstudent',
            name='Dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centreregisterstudent',
            name='dateofissue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centreregisterstudent',
            name='duration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centreregisterstudent',
            name='examheldon',
            field=models.DateField(blank=True, null=True),
        ),
    ]
