# Generated by Django 4.2.1 on 2023-06-10 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ineffable_app', '0014_alter_centreregisterstudent_dob_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CentreRegisterStudent',
        ),
    ]
