# Generated by Django 4.2.1 on 2023-06-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ineffable_app', '0016_centreregisterstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('student_id', models.IntegerField()),
                ('student_rollno', models.IntegerField()),
            ],
        ),
    ]
